# Generated by Django 5.2.1 on 2025-06-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryinfo',
            name='BakeryName',
            field=models.CharField(max_length=64),
        ),
    ]
