# Generated by Django 5.2.1 on 2025-06-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryHome', '0002_alter_bakeryinfo_bakeryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodType', models.CharField(max_length=64)),
                ('FoodPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
