# Generated by Django 5.2.1 on 2025-06-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryHome', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(default=-8223, max_length=25)),
                ('contactEmail', models.EmailField(default='test@gmail.com', max_length=64)),
            ],
        ),
    ]
