# Generated by Django 5.2.1 on 2025-06-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryHome', '0004_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryinfo',
            name='BakeryDescription',
            field=models.TextField(default=''),
        ),
    ]
