# Generated by Django 5.2.1 on 2025-06-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeryHome', '0005_bakeryinfo_bakerydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='FoodImage',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='FoodType',
            field=models.CharField(default='', max_length=64),
        ),
    ]
